### ISSUE TITLE
Request: Add demo URL to repository

### ISSUE THREAD

**Issue by ayoubelmhamdi** [SichangHe/mdbook_katex_static_css#1]
Thank you for creating and sharing this repository. 

I think it would be really helpful if there was a demo URL available so that users could see the functionality of the project in action. Would it be possible to add one?

**Comment by SichangHe** [comment]
I am so confused because I don't think I shared this repository.

This repository is a work in progress. The `no-css` option has not been release from `mdbook-katex`.

I will include GitHub pages setup and link to the GitHub pages. Is that what you mean by "demo URL?"

**Comment by ayoubelmhamdi** [comment]
I search for this demo `https://sichanghe.github.io/mdbook_katex_static_css/`, so think's

**Comment by SichangHe** [comment]
Sorry, I could not understand what you mean. Could you reexplain it?

**Comment by ayoubelmhamdi** [comment]
Without a live demo, we would need to read all the code in your repository to understand why it’s useful. A live demo could be an URL that proves the usefulness of this repository.

**Comment by SichangHe** [comment]
> Without a live demo, we would need to read all the code in your repository to understand why it’s useful.

Please see [Self-host KaTeX CSS and fonts in `mdbook-katex` README](https://github.com/lzanini/mdbook-katex#self-host-katex-css-and-fonts) to understand why it's useful.

You don't need to read all the code. We have documentations.

If you have other questions, please open another issue with a more specific title.
